name: Build Scan Push Image 

on:
  workflow_dispatch:  # Ruƒçno pokretanje

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
        
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t myapp:${{github.sha}} .
          #docker tag myapp:${{github.sha}} ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{github.sha}}

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myapp:${{github.sha}}'
          format: 'table'
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Push Docker image to DockerHub
        if: success()
        run: |
          docker tag myapp:${{github.sha}} ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${GITHUB_SHA::8}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${GITHUB_SHA::8}
